### ISSUE TITLE
Is this project still alive? What is  relationship with ML.NET?

### ISSUE THREAD

**Issue by sharpwood** [Microsoft/NativeKeras#1]

**Comment by ivannp** [comment]
No relationship to ML.NET. It can be used for the tasks covered in the documentation, but it has been quiet for a while.

**Comment by deepakkumar1984** [comment]
Many projects started with csharp for deep learning but doesn't go any far due to lack of support.

**Comment by sharpwood** [comment]
I hope ML.net can support the training of deep learning projects as soon as possible.
